import LayoutComponent from '@/components/Layout/LayoutComponent'
import { urbanist } from '@/utils/font'
import 'swiper/css'
import 'swiper/css/scrollbar'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta name='robots' content='noindex,nofollow' />
      </head>

      <body className={urbanist.className}>
        <LayoutComponent>{children}</LayoutComponent>
      </body>
    </html>
  )
}
