'use client'

import StyledComponentsRegistry from '@/app/registry';
import {urbanist} from '@/utils/font'
import 'swiper/css'
import 'swiper/css/scrollbar'

// import '@/styles/index.scss'
import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer';
import GlobalStyle from '@/styles/globalStyles';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <StyledComponentsRegistry>
      <body className={urbanist.className}>
      <GlobalStyle/>
      <Header/>

      {children}

      <Footer/>
      </body>
    </StyledComponentsRegistry>

    </html>
  )
}
