'use client'

import { useEffect, useState } from 'react'
import { usePathname } from 'next/navigation'
import BreadCrumbs from '@/components/BreadCrumbs'
import { getUrlForBreadCrumbs } from '@/utils/getUrlForBreadCrumbs'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [pages, setPages] = useState([])

  const pagesBlogs = [
    { name: 'Home page', href: '/' },
    { name: 'Insights', href: '/blog' },
  ]

  const pagesBlog = [
    { name: 'Home page', href: '/' },
    { name: 'Insights', href: '/blog' },
    { name: 'How to Sell Cryptocurrencies on Our Platform', href: '/1' },
  ]

  const pathname = usePathname()

  useEffect(() => {
    const path = getUrlForBreadCrumbs(pathname)
    setPages(path.length === 2 ? pagesBlog : pagesBlogs)
  }, [pathname])

  return (
    <div>
      <BreadCrumbs pages={pages} />

      {children}
    </div>
  )
}
