'use client'

import BreadCrumbs from '@/components/BreadCrumbs';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({children}) {
  const pages = [
    {name: 'Home page', href: '/'},
    {name: 'Insights', href: '/blog'},
  ]

  return (
    <div>
      <BreadCrumbs pages={pages}/>
      
      {children}
    </div>
  )
}
