// import { useLocale } from 'next-intl'
// import { notFound } from 'next/navigation'

import LayoutComponent from '@/components/Layout/LayoutComponent';
import { urbanist } from '@/utils/font';

import 'swiper/css';
import 'swiper/css/scrollbar';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default async function RootLayout({ children, params }) {
  // const locale = useLocale()

  let messages;
  try {
    messages = (await import(`../../dictionaries/${params.locale}.json`))
      .default;
  } catch (error) {
    // notFound()
  }

  return (
    <html lang={params.locale}>
      <head>
        <meta name="title" content="Ingud" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="robots" content="noindex,nofollow" />
      </head>

      <body className={urbanist.className}>
        <LayoutComponent messages={messages} locale={params.locale}>
          {children}
        </LayoutComponent>
      </body>
    </html>
  );
}
